//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElbrusSkiResort.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeSet()
        {
            this.LoginHistorySet = new HashSet<LoginHistorySet>();
        }
    
        public int EmployeeCode { get; set; }
        public string Post { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }

        public string GetFullName
        {
            get
            {
                return $"ФИО: {this.Surname} {this.Name} {this.Patronymic}";
            }
        }

        public string GetImage
        {
            get
            {
                return "/Resources/" + this.Surname + ".jpeg";
            }
        }

        public string GetRole
        {
            get
            {
                return $"Роль: {this.Post}";
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginHistorySet> LoginHistorySet { get; set; }
    }
}
