//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElbrusSkiResort.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderService
    {
        public int Id { get; set; }
        public int Order_Id { get; set; }
        public int Service_Id { get; set; }
    
        public virtual OrderSet OrderSet { get; set; }
        public virtual ServiceSet ServiceSet { get; set; }
    }
}
