//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElbrusSkiResort.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrielbrusyeDBEntities : DbContext
    {
        public PrielbrusyeDBEntities()
            : base("name=PrielbrusyeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientSet> ClientSet { get; set; }
        public virtual DbSet<EmployeeSet> EmployeeSet { get; set; }
        public virtual DbSet<LoginHistorySet> LoginHistorySet { get; set; }
        public virtual DbSet<OrderService> OrderService { get; set; }
        public virtual DbSet<OrderSet> OrderSet { get; set; }
        public virtual DbSet<ServiceSet> ServiceSet { get; set; }
    }
}
